# Minio docker-compose
services:
  minio:
    build: ./minio
    container_name: brazil-wildfires-minio
    ports:
      - '${MINIO_API_PORT}:${MINIO_API_PORT}'
      - '${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}'
    volumes:
      - ./minio/data:/data
    networks:
      - brazil-wildfires-network
    environment:
      MINIO_ROOT_USER: '${MINIO_ROOT_USER}'
      MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD}'
      MINIO_ADDRESS: ':${MINIO_API_PORT}'
      MINIO_CONSOLE_ADDRESS: ':${MINIO_CONSOLE_PORT}'

networks:
  brazil-wildfires-network:
    driver: bridge